<?php

namespace ContainerDQHmieo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O8rj19LService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.O8rj19L' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.O8rj19L'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'auditService' => ['privates', 'App\\Service\\AuditService', 'getAuditServiceService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'user' => ['privates', '.errored..service_locator.O8rj19L.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.O8rj19L": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'auditService' => 'App\\Service\\AuditService',
            'entityManager' => '?',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
