<?php

namespace ContainerDQHmieo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7fwuAGPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7fwuAGP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7fwuAGP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'moduloRepository' => ['privates', 'App\\Repository\\ModuloRepository', 'getModuloRepositoryService', true],
            'permissaoRepository' => ['privates', 'App\\Repository\\PermissaoRepository', 'getPermissaoRepositoryService', true],
            'usuario' => ['privates', '.errored..service_locator.7fwuAGP.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.7fwuAGP": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'moduloRepository' => 'App\\Repository\\ModuloRepository',
            'permissaoRepository' => 'App\\Repository\\PermissaoRepository',
            'usuario' => 'App\\Entity\\User',
        ]);
    }
}
