<?php

namespace ContainerDQHmieo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApp_UserProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'app.user_provider' shared autowired service.
     *
     * @return \App\Security\UserProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/User/UserProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Security/UserProvider.php';

        return $container->privates['app.user_provider'] = new \App\Security\UserProvider(($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')));
    }
}
