<?php

namespace ContainerDQHmieo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateInitialModulesCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CreateInitialModulesCommand' shared autowired service.
     *
     * @return \App\Command\CreateInitialModulesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/CreateInitialModulesCommand.php';

        $container->privates['App\\Command\\CreateInitialModulesCommand'] = $instance = new \App\Command\CreateInitialModulesCommand(($container->privates['App\\Repository\\ModuloRepository'] ?? $container->load('getModuloRepositoryService')));

        $instance->setName('app:create-initial-modules');
        $instance->setDescription('Cria os módulos iniciais do sistema');

        return $instance;
    }
}
