<?php

namespace ContainerDQHmieo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateInitialCaixaDataCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\CreateInitialCaixaDataCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\CreateInitialCaixaDataCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:create-initial-caixa-data', [], 'Cria dados iniciais para o sistema de caixa', false, #[\Closure(name: 'App\\Command\\CreateInitialCaixaDataCommand')] fn (): \App\Command\CreateInitialCaixaDataCommand => ($container->privates['App\\Command\\CreateInitialCaixaDataCommand'] ?? $container->load('getCreateInitialCaixaDataCommandService')));
    }
}
