<?php

namespace ContainerDQHmieo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateInitialCaixaDataCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CreateInitialCaixaDataCommand' shared autowired service.
     *
     * @return \App\Command\CreateInitialCaixaDataCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/CreateInitialCaixaDataCommand.php';

        $container->privates['App\\Command\\CreateInitialCaixaDataCommand'] = $instance = new \App\Command\CreateInitialCaixaDataCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:create-initial-caixa-data');
        $instance->setDescription('Cria dados iniciais para o sistema de caixa');

        return $instance;
    }
}
