<?php

namespace ContainerDQHmieo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPermissao2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ypJ1VUj.App\Entity\Permissao' shared service.
     *
     * @return \App\Entity\Permissao
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ypJ1VUj": it needs an instance of "App\\Entity\\Permissao" but this type has been excluded in "config/services.yaml".');
    }
}
