<?php

namespace ContainerDQHmieo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestCaixaAccessCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\TestCaixaAccessCommand' shared autowired service.
     *
     * @return \App\Command\TestCaixaAccessCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/TestCaixaAccessCommand.php';

        $container->privates['App\\Command\\TestCaixaAccessCommand'] = $instance = new \App\Command\TestCaixaAccessCommand(($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['debug.security.access.decision_manager'] ?? self::getDebug_Security_Access_DecisionManagerService($container)));

        $instance->setName('app:test-caixa-access');
        $instance->setDescription('Testa acesso ao módulo de caixa');

        return $instance;
    }
}
