<?php

namespace ContainerDQHmieo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestCaixaAccessCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\TestCaixaAccessCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\TestCaixaAccessCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:test-caixa-access', [], 'Testa acesso ao módulo de caixa', false, #[\Closure(name: 'App\\Command\\TestCaixaAccessCommand')] fn (): \App\Command\TestCaixaAccessCommand => ($container->privates['App\\Command\\TestCaixaAccessCommand'] ?? $container->load('getTestCaixaAccessCommandService')));
    }
}
