<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Modulo extends \App\Entity\Modulo implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'ativo' => [parent::class, 'ativo', null, 16],
        "\0".parent::class."\0".'codigo' => [parent::class, 'codigo', null, 16],
        "\0".parent::class."\0".'dataCriacao' => [parent::class, 'dataCriacao', null, 16],
        "\0".parent::class."\0".'descricao' => [parent::class, 'descricao', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'nome' => [parent::class, 'nome', null, 16],
        "\0".parent::class."\0".'permissoes' => [parent::class, 'permissoes', null, 16],
        'ativo' => [parent::class, 'ativo', null, 16],
        'codigo' => [parent::class, 'codigo', null, 16],
        'dataCriacao' => [parent::class, 'dataCriacao', null, 16],
        'descricao' => [parent::class, 'descricao', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'nome' => [parent::class, 'nome', null, 16],
        'permissoes' => [parent::class, 'permissoes', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
