<?php

namespace Container6WJ79O8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YpJ1VUjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ypJ1VUj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ypJ1VUj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'permissao' => ['privates', '.errored..service_locator.ypJ1VUj.App\\Entity\\Permissao', NULL, 'Cannot autowire service ".service_locator.ypJ1VUj": it needs an instance of "App\\Entity\\Permissao" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'permissao' => 'App\\Entity\\Permissao',
        ]);
    }
}
