<?php

namespace Container6WJ79O8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JKavS3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._JKavS3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._JKavS3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'moduloRepository' => ['privates', 'App\\Repository\\ModuloRepository', 'getModuloRepositoryService', true],
        ], [
            'moduloRepository' => 'App\\Repository\\ModuloRepository',
        ]);
    }
}
