<?php

namespace Container6WJ79O8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ne38N_MService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ne38N.M' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ne38N.M'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'modulo' => ['privates', '.errored..service_locator.Ne38N.M.App\\Entity\\Modulo', NULL, 'Cannot autowire service ".service_locator.Ne38N.M": it needs an instance of "App\\Entity\\Modulo" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'modulo' => 'App\\Entity\\Modulo',
        ]);
    }
}
