<?php

namespace Container6WJ79O8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UeHim4XService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UeHim4X' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UeHim4X'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'auditService' => ['privates', 'App\\Service\\AuditService', 'getAuditServiceService', true],
            'caixa' => ['privates', '.errored..service_locator.UeHim4X.App\\Entity\\Caixa', NULL, 'Cannot autowire service ".service_locator.UeHim4X": it needs an instance of "App\\Entity\\Caixa" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'auditService' => 'App\\Service\\AuditService',
            'caixa' => 'App\\Entity\\Caixa',
            'entityManager' => '?',
        ]);
    }
}
