<?php

namespace Container6WJ79O8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RkuHH3zService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RkuHH3z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RkuHH3z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'permissaoRepository' => ['privates', 'App\\Repository\\PermissaoRepository', 'getPermissaoRepositoryService', true],
        ], [
            'permissaoRepository' => 'App\\Repository\\PermissaoRepository',
        ]);
    }
}
