<?php

namespace Container6WJ79O8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FzSu_ZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fzSu.Z_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fzSu.Z_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'permissao' => ['privates', '.errored..service_locator.fzSu.Z_.App\\Entity\\Permissao', NULL, 'Cannot autowire service ".service_locator.fzSu.Z_": it needs an instance of "App\\Entity\\Permissao" but this type has been excluded in "config/services.yaml".'],
        ], [
            'permissao' => 'App\\Entity\\Permissao',
        ]);
    }
}
