<?php

namespace Container6WJ79O8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ImD68zLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ImD68zL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ImD68zL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'auditLogRepository' => ['privates', 'App\\Repository\\AuditLogRepository', 'getAuditLogRepositoryService', true],
        ], [
            'auditLogRepository' => 'App\\Repository\\AuditLogRepository',
        ]);
    }
}
