<?php

namespace Container6WJ79O8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__NLdMA9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..NLdMA9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..NLdMA9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'modulo' => ['privates', '.errored..service_locator..NLdMA9.App\\Entity\\Modulo', NULL, 'Cannot autowire service ".service_locator..NLdMA9": it needs an instance of "App\\Entity\\Modulo" but this type has been excluded in "config/services.yaml".'],
        ], [
            'modulo' => 'App\\Entity\\Modulo',
        ]);
    }
}
