<?php

namespace Container6WJ79O8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddCaixaPermissionsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\AddCaixaPermissionsCommand' shared autowired service.
     *
     * @return \App\Command\AddCaixaPermissionsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/AddCaixaPermissionsCommand.php';

        $container->privates['App\\Command\\AddCaixaPermissionsCommand'] = $instance = new \App\Command\AddCaixaPermissionsCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['App\\Repository\\ModuloRepository'] ?? $container->load('getModuloRepositoryService')));

        $instance->setName('app:add-caixa-permissions');
        $instance->setDescription('Adiciona permissões do módulo CAIXA para usuários');

        return $instance;
    }
}
