<?php

namespace Container6WJ79O8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateInitialModulesCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\CreateInitialModulesCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\CreateInitialModulesCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:create-initial-modules', [], 'Cria os módulos iniciais do sistema', false, #[\Closure(name: 'App\\Command\\CreateInitialModulesCommand')] fn (): \App\Command\CreateInitialModulesCommand => ($container->privates['App\\Command\\CreateInitialModulesCommand'] ?? $container->load('getCreateInitialModulesCommandService')));
    }
}
