<?php

namespace Container6WJ79O8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateAdminUserCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\CreateAdminUserCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\CreateAdminUserCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:create-admin-user', [], 'Cria um usuário administrador', false, #[\Closure(name: 'App\\Command\\CreateAdminUserCommand')] fn (): \App\Command\CreateAdminUserCommand => ($container->privates['App\\Command\\CreateAdminUserCommand'] ?? $container->load('getCreateAdminUserCommandService')));
    }
}
