<?php

namespace Container6WJ79O8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCaixaControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Caixa\CaixaController' shared autowired service.
     *
     * @return \App\Controller\Caixa\CaixaController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Caixa/CaixaController.php';

        $container->services['App\\Controller\\Caixa\\CaixaController'] = $instance = new \App\Controller\Caixa\CaixaController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Caixa\\CaixaController', $container));

        return $instance;
    }
}
