<?php

namespace Container6WJ79O8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCaixa2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.wrH43Y..App\Entity\Caixa' shared service.
     *
     * @return \App\Entity\Caixa
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.wrH43Y.": it needs an instance of "App\\Entity\\Caixa" but this type has been excluded in "config/services.yaml".');
    }
}
