<?php

namespace Container6WJ79O8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPermissaoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.fzSu.Z_.App\Entity\Permissao' shared service.
     *
     * @return \App\Entity\Permissao
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.fzSu.Z_": it needs an instance of "App\\Entity\\Permissao" but this type has been excluded in "config/services.yaml".');
    }
}
